// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Primary design header
//
// This header should be included by all source files instantiating the design.
// The class here is then constructed to instantiate the design.
// See the Verilator manual for examples.

#ifndef _VVGA_LED_H_
#define _VVGA_LED_H_

#include "verilated.h"
#include "VVGA_LED__Inlines.h"
class VVGA_LED__Syms;
class VerilatedVcd;

//----------

VL_MODULE(VVGA_LED) {
  public:
    // CELLS
    // Public to allow access to /*verilator_public*/ items;
    // otherwise the application code can consider these internals.
    
    // PORTS
    // The application code writes and reads these signals to
    // propagate new values into/out from the Verilated model.
    VL_IN8(clk,0,0);
    VL_IN8(reset,0,0);
    VL_IN8(write,0,0);
    VL_IN8(read,0,0);
    VL_IN8(chipselect,0,0);
    VL_IN8(address,3,0);
    VL_OUT8(VGA_R,7,0);
    VL_OUT8(VGA_G,7,0);
    VL_OUT8(VGA_B,7,0);
    VL_OUT8(VGA_CLK,0,0);
    VL_OUT8(VGA_HS,0,0);
    VL_OUT8(VGA_VS,0,0);
    VL_OUT8(VGA_BLANK_n,0,0);
    VL_OUT8(VGA_SYNC_n,0,0);
    //char	__VpadToAlign14[2];
    VL_IN(writedata,31,0);
    VL_OUT(readdata,31,0);
    
    // LOCAL SIGNALS
    // Internals; generally not touched by application code
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(v__DOT__fifo_rd1,0,0);
    VL_SIG8(v__DOT__fifo_rd2,0,0);
    VL_SIG8(v__DOT__fifo_rd3,0,0);
    VL_SIG8(v__DOT__fifo_wr1,0,0);
    VL_SIG8(v__DOT__fifo_wr2,0,0);
    VL_SIG8(v__DOT__fifo_wr3,0,0);
    VL_SIG8(v__DOT__input_ram_rden1,0,0);
    VL_SIG8(v__DOT__input_ram_rden2,0,0);
    VL_SIG8(v__DOT__input_ram_rden3,0,0);
    VL_SIG8(v__DOT__input_ram_wren1,0,0);
    VL_SIG8(v__DOT__input_ram_wren2,0,0);
    VL_SIG8(v__DOT__input_ram_wren3,0,0);
    VL_SIG8(v__DOT__out_ram_wr1,0,0);
    VL_SIG8(v__DOT__out_ram_wr2,0,0);
    VL_SIG8(v__DOT__out_ram_wr3,0,0);
    VL_SIG8(v__DOT__mux_sel1,1,0);
    VL_SIG8(v__DOT__mux_sel2,1,0);
    VL_SIG8(v__DOT__mux_sel3,1,0);
    VL_SIG8(v__DOT__hex1,7,0);
    VL_SIG8(v__DOT__hex2,7,0);
    VL_SIG8(v__DOT__hex3,7,0);
    VL_SIG8(v__DOT__hex4,7,0);
    VL_SIG8(v__DOT__hex5,7,0);
    VL_SIG8(v__DOT__hex6,7,0);
    VL_SIG8(v__DOT__fifo_out0,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__temp,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_wren_reg_a,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_wren_reg_b,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_rden_reg_a,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_rden_reg_b,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_read_flag_a,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_read_flag_b,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_write_flag_b,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__good_to_go_a,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__good_to_go_b,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__init_file_b_port,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_nmram_write_a,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_nmram_write_b,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__same_clock_pulse0,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__same_clock_pulse1,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_address_aclr_a_flag,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_address_aclr_a_prev,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_address_aclr_b_flag,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_address_aclr_b_prev,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_outdata_aclr_a_prev,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_outdata_aclr_b_prev,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_force_reread_a,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_force_reread_a1,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_force_reread_b,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_force_reread_b1,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_force_reread_a_signal,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_force_reread_b_signal,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_good_to_write_a,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_good_to_write_a2,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_good_to_write_b2,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_core_clocken_a_reg,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_core_clocken0_b_reg,0,0);
    VL_SIG8(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_core_clocken1_b_reg,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__temp,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_wren_reg_a,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_wren_reg_b,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_rden_reg_a,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_rden_reg_b,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_read_flag_a,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_read_flag_b,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_write_flag_b,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__good_to_go_a,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__good_to_go_b,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__init_file_b_port,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_nmram_write_a,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_nmram_write_b,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__same_clock_pulse0,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__same_clock_pulse1,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_address_aclr_a_flag,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_address_aclr_a_prev,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_address_aclr_b_flag,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_address_aclr_b_prev,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_outdata_aclr_a_prev,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_outdata_aclr_b_prev,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_force_reread_a,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_force_reread_a1,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_force_reread_b,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_force_reread_b1,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_force_reread_a_signal,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_force_reread_b_signal,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_good_to_write_a,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_good_to_write_a2,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_good_to_write_b2,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_core_clocken_a_reg,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_core_clocken0_b_reg,0,0);
    VL_SIG8(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_core_clocken1_b_reg,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__temp,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_wren_reg_a,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_wren_reg_b,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_rden_reg_a,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_rden_reg_b,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_read_flag_a,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_read_flag_b,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_write_flag_b,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__good_to_go_a,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__good_to_go_b,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__init_file_b_port,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_nmram_write_a,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_nmram_write_b,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__same_clock_pulse0,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__same_clock_pulse1,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_address_aclr_a_flag,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_address_aclr_a_prev,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_address_aclr_b_flag,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_address_aclr_b_prev,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_outdata_aclr_a_prev,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_outdata_aclr_b_prev,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_force_reread_a,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_force_reread_a1,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_force_reread_b,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_force_reread_b1,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_force_reread_a_signal,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_force_reread_b_signal,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_good_to_write_a,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_good_to_write_a2,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_good_to_write_b2,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_core_clocken_a_reg,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_core_clocken0_b_reg,0,0);
    VL_SIG8(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_core_clocken1_b_reg,0,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__sclr,0,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__count_id,1,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__read_id,1,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__write_id,1,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__valid_rreq,0,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__valid_wreq,0,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__write_flag,0,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__full_flag,0,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__empty_flag,0,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__almost_full_flag,0,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__almost_empty_flag,0,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__stratix_family,0,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__set_q_to_x,0,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__set_q_to_x_by_empty,0,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__write_latency1,1,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__write_latency2,1,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__write_latency3,1,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__empty_latency1,0,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__empty_latency2,0,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__data_ready,3,0);
    VL_SIG8(v__DOT__fifo1__DOT__scfifo_component__DOT__data_shown,3,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__sclr,0,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__count_id,1,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__read_id,1,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__write_id,1,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__valid_rreq,0,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__valid_wreq,0,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__write_flag,0,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__full_flag,0,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__empty_flag,0,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__almost_full_flag,0,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__almost_empty_flag,0,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__stratix_family,0,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__set_q_to_x,0,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__set_q_to_x_by_empty,0,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__write_latency1,1,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__write_latency2,1,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__write_latency3,1,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__empty_latency1,0,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__empty_latency2,0,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__data_ready,3,0);
    VL_SIG8(v__DOT__fifo2__DOT__scfifo_component__DOT__data_shown,3,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__sclr,0,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__count_id,1,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__read_id,1,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__write_id,1,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__valid_rreq,0,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__valid_wreq,0,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__write_flag,0,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__full_flag,0,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__empty_flag,0,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__almost_full_flag,0,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__almost_empty_flag,0,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__stratix_family,0,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__set_q_to_x,0,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__set_q_to_x_by_empty,0,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__write_latency1,1,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__write_latency2,1,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__write_latency3,1,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__empty_latency1,0,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__empty_latency2,0,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__data_ready,3,0);
    VL_SIG8(v__DOT__fifo3__DOT__scfifo_component__DOT__data_shown,3,0);
    VL_SIG8(v__DOT__scheduler__DOT__write_cycle,0,0);
    VL_SIG8(v__DOT__scheduler__DOT__ram_not_empty1,0,0);
    VL_SIG8(v__DOT__scheduler__DOT__ram_not_empty2,0,0);
    VL_SIG8(v__DOT__scheduler__DOT__ram_not_empty3,0,0);
    VL_SIG8(v__DOT__scheduler__DOT__read1,0,0);
    VL_SIG8(v__DOT__scheduler__DOT__read2,0,0);
    VL_SIG8(v__DOT__scheduler__DOT__read3,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram_rd1,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram_rd2,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram_rd3,0,0);
    VL_SIG8(v__DOT__buffer__DOT__read_cycle1,0,0);
    VL_SIG8(v__DOT__buffer__DOT__read_cycle2,0,0);
    VL_SIG8(v__DOT__buffer__DOT__read_cycle3,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__temp,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_wren_reg_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_wren_reg_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_rden_reg_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_rden_reg_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_read_flag_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_read_flag_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_write_flag_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__good_to_go_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__good_to_go_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__init_file_b_port,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_nmram_write_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_nmram_write_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__same_clock_pulse0,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__same_clock_pulse1,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_address_aclr_a_flag,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_address_aclr_a_prev,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_address_aclr_b_flag,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_address_aclr_b_prev,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_outdata_aclr_a_prev,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_outdata_aclr_b_prev,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_force_reread_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_force_reread_a1,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_force_reread_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_force_reread_b1,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_force_reread_a_signal,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_force_reread_b_signal,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_good_to_write_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_good_to_write_a2,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_good_to_write_b2,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_core_clocken_a_reg,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_core_clocken0_b_reg,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_core_clocken1_b_reg,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__temp,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_wren_reg_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_wren_reg_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_rden_reg_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_rden_reg_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_read_flag_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_read_flag_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_write_flag_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__good_to_go_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__good_to_go_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__init_file_b_port,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_nmram_write_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_nmram_write_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__same_clock_pulse0,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__same_clock_pulse1,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_address_aclr_a_flag,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_address_aclr_a_prev,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_address_aclr_b_flag,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_address_aclr_b_prev,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_outdata_aclr_a_prev,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_outdata_aclr_b_prev,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_force_reread_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_force_reread_a1,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_force_reread_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_force_reread_b1,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_force_reread_a_signal,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_force_reread_b_signal,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_good_to_write_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_good_to_write_a2,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_good_to_write_b2,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_core_clocken_a_reg,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_core_clocken0_b_reg,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_core_clocken1_b_reg,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__temp,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_wren_reg_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_wren_reg_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_rden_reg_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_rden_reg_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_read_flag_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_read_flag_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_write_flag_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__good_to_go_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__good_to_go_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__init_file_b_port,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_nmram_write_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_nmram_write_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__same_clock_pulse0,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__same_clock_pulse1,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_address_aclr_a_flag,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_address_aclr_a_prev,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_address_aclr_b_flag,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_address_aclr_b_prev,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_outdata_aclr_a_prev,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_outdata_aclr_b_prev,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_force_reread_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_force_reread_a1,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_force_reread_b,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_force_reread_b1,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_force_reread_a_signal,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_force_reread_b_signal,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_good_to_write_a,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_good_to_write_a2,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_good_to_write_b2,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_core_clocken_a_reg,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_core_clocken0_b_reg,0,0);
    VL_SIG8(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_core_clocken1_b_reg,0,0);
    VL_SIG8(v__DOT__packet_Display__DOT__topCol,0,0);
    VL_SIG8(v__DOT__packet_Display__DOT__botCol,0,0);
    VL_SIG8(v__DOT__packet_Display__DOT__segment,7,0);
    VL_SIG16(v__DOT__input_ram_rd_add1,11,0);
    VL_SIG16(v__DOT__input_ram_rd_add2,11,0);
    VL_SIG16(v__DOT__input_ram_rd_add3,11,0);
    VL_SIG16(v__DOT__input_ram_wr_add1,11,0);
    VL_SIG16(v__DOT__input_ram_wr_add2,11,0);
    VL_SIG16(v__DOT__input_ram_wr_add3,11,0);
    VL_SIG16(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_address_reg_a,11,0);
    VL_SIG16(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_address_reg_b,11,0);
    VL_SIG16(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_original_address_a,11,0);
    VL_SIG16(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_address_reg_a,11,0);
    VL_SIG16(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_address_reg_b,11,0);
    VL_SIG16(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_original_address_a,11,0);
    VL_SIG16(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_address_reg_a,11,0);
    VL_SIG16(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_address_reg_b,11,0);
    VL_SIG16(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_original_address_a,11,0);
    VL_SIG16(v__DOT__buffer__DOT__ram_wr_add1,11,0);
    VL_SIG16(v__DOT__buffer__DOT__ram_wr_add2,11,0);
    VL_SIG16(v__DOT__buffer__DOT__ram_wr_add3,11,0);
    VL_SIG16(v__DOT__buffer__DOT__ram_rd_add1,11,0);
    VL_SIG16(v__DOT__buffer__DOT__ram_rd_add2,11,0);
    VL_SIG16(v__DOT__buffer__DOT__ram_rd_add3,11,0);
    VL_SIG16(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_address_reg_a,11,0);
    VL_SIG16(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_address_reg_b,11,0);
    VL_SIG16(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_original_address_a,11,0);
    VL_SIG16(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_address_reg_a,11,0);
    VL_SIG16(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_address_reg_b,11,0);
    VL_SIG16(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_original_address_a,11,0);
    VL_SIG16(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_address_reg_a,11,0);
    VL_SIG16(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_address_reg_b,11,0);
    VL_SIG16(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_original_address_a,11,0);
    VL_SIG(v__DOT__fifo_in1,31,0);
    VL_SIG(v__DOT__fifo_in2,31,0);
    VL_SIG(v__DOT__fifo_in3,31,0);
    VL_SIG(v__DOT__input_ram_wr_in1,31,0);
    VL_SIG(v__DOT__input_ram_wr_in2,31,0);
    VL_SIG(v__DOT__input_ram_wr_in3,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_data_reg_a,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__temp_wa,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__temp_wa2,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__temp_wa2b,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__init_temp,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_data_reg_b,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__temp_wb,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__temp_wb2,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_q_reg_a,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_q_tmp_a,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_q_tmp2_a,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_q_reg_b,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_q_tmp_b,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_q_tmp2_b,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_q_output_latch,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_q_ecc_reg_b,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_q_ecc_tmp_b,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_tmp,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_tmp,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_out,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_out,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_x,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_x,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_out_b,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_out_a,31,0);
    VL_SIGW(v__DOT__input_ram1__DOT__altsyncram_component__DOT__ram_initf,2048,1,64);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__file_desc,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__wa_mult_x,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__wa_mult_x_ii,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__wa_mult_x_iii,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_original_data_b,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_original_data_a,31,0);
    VL_SIGW(v__DOT__input_ram1__DOT__altsyncram_component__DOT__cread_during_write_mode_mixed_ports,168,0,6);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_byte_size,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_numwords_a,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_numwords_b,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_aclr_flag_a,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_aclr_flag_b,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_q_tmp2_a_idx,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__init_i,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i2,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i3,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i4,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i5,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__j,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__j2,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__j3,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__k,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__k2,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__k3,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__k4,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_div_wa,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_div_wb,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__j_plus_i2,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__j2_plus_i5,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__j3_plus_i5,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__j_plus_i2_div_a,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__j2_plus_i5_div_a,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__j3_plus_i5_div_a,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__j3_plus_i5_div_b,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_byteena_count,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__port_a_bit_count_low,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__port_a_bit_count_high,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__port_b_bit_count_low,31,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__port_b_bit_count_high,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_data_reg_a,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__temp_wa,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__temp_wa2,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__temp_wa2b,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__init_temp,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_data_reg_b,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__temp_wb,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__temp_wb2,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_q_reg_a,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_q_tmp_a,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_q_tmp2_a,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_q_reg_b,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_q_tmp_b,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_q_tmp2_b,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_q_output_latch,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_q_ecc_reg_b,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_q_ecc_tmp_b,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_tmp,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_tmp,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_out,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_out,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_x,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_x,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_out_b,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_out_a,31,0);
    VL_SIGW(v__DOT__input_ram2__DOT__altsyncram_component__DOT__ram_initf,2048,1,64);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__file_desc,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__wa_mult_x,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__wa_mult_x_ii,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__wa_mult_x_iii,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_original_data_b,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_original_data_a,31,0);
    VL_SIGW(v__DOT__input_ram2__DOT__altsyncram_component__DOT__cread_during_write_mode_mixed_ports,168,0,6);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_byte_size,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_numwords_a,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_numwords_b,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_aclr_flag_a,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_aclr_flag_b,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_q_tmp2_a_idx,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__init_i,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i2,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i3,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i4,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i5,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__j,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__j2,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__j3,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__k,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__k2,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__k3,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__k4,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_div_wa,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_div_wb,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__j_plus_i2,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__j2_plus_i5,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__j3_plus_i5,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__j_plus_i2_div_a,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__j2_plus_i5_div_a,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__j3_plus_i5_div_a,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__j3_plus_i5_div_b,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_byteena_count,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__port_a_bit_count_low,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__port_a_bit_count_high,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__port_b_bit_count_low,31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__port_b_bit_count_high,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_data_reg_a,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__temp_wa,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__temp_wa2,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__temp_wa2b,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__init_temp,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_data_reg_b,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__temp_wb,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__temp_wb2,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_q_reg_a,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_q_tmp_a,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_q_tmp2_a,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_q_reg_b,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_q_tmp_b,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_q_tmp2_b,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_q_output_latch,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_q_ecc_reg_b,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_q_ecc_tmp_b,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_tmp,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_tmp,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_out,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_out,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_x,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_x,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_out_b,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_out_a,31,0);
    VL_SIGW(v__DOT__input_ram3__DOT__altsyncram_component__DOT__ram_initf,2048,1,64);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__file_desc,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__wa_mult_x,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__wa_mult_x_ii,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__wa_mult_x_iii,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_original_data_b,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_original_data_a,31,0);
    VL_SIGW(v__DOT__input_ram3__DOT__altsyncram_component__DOT__cread_during_write_mode_mixed_ports,168,0,6);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_byte_size,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_numwords_a,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_numwords_b,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_aclr_flag_a,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_aclr_flag_b,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_q_tmp2_a_idx,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__init_i,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i2,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i3,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i4,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i5,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__j,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__j2,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__j3,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__k,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__k2,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__k3,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__k4,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_div_wa,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_div_wb,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__j_plus_i2,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__j2_plus_i5,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__j3_plus_i5,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__j_plus_i2_div_a,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__j2_plus_i5_div_a,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__j3_plus_i5_div_a,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__j3_plus_i5_div_b,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_byteena_count,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__port_a_bit_count_low,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__port_a_bit_count_high,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__port_b_bit_count_low,31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__port_b_bit_count_high,31,0);
    VL_SIG(v__DOT__fifo1__DOT__scfifo_component__DOT__tmp_q,31,0);
    VL_SIG(v__DOT__fifo1__DOT__scfifo_component__DOT__wrt_count,31,0);
    VL_SIG(v__DOT__fifo1__DOT__scfifo_component__DOT__i,31,0);
    VL_SIG(v__DOT__fifo2__DOT__scfifo_component__DOT__tmp_q,31,0);
    VL_SIG(v__DOT__fifo2__DOT__scfifo_component__DOT__wrt_count,31,0);
    VL_SIG(v__DOT__fifo2__DOT__scfifo_component__DOT__i,31,0);
    VL_SIG(v__DOT__fifo3__DOT__scfifo_component__DOT__tmp_q,31,0);
    VL_SIG(v__DOT__fifo3__DOT__scfifo_component__DOT__wrt_count,31,0);
    VL_SIG(v__DOT__fifo3__DOT__scfifo_component__DOT__i,31,0);
    VL_SIGW(v__DOT__megamux1__DOT__sub_wire2,127,0,4);
    VL_SIG(v__DOT__megamux1__DOT__LPM_MUX_component__DOT__tmp_result,31,0);
    VL_SIG(v__DOT__megamux1__DOT__LPM_MUX_component__DOT__i,31,0);
    VL_SIG(v__DOT__megamux2__DOT__LPM_MUX_component__DOT__tmp_result,31,0);
    VL_SIG(v__DOT__megamux2__DOT__LPM_MUX_component__DOT__i,31,0);
    VL_SIG(v__DOT__megamux3__DOT__LPM_MUX_component__DOT__tmp_result,31,0);
    VL_SIG(v__DOT__megamux3__DOT__LPM_MUX_component__DOT__i,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_data_reg_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__temp_wa,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__temp_wa2,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__temp_wa2b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__init_temp,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_data_reg_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__temp_wb,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__temp_wb2,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_q_reg_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_q_tmp_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_q_tmp2_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_q_reg_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_q_tmp_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_q_tmp2_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_q_output_latch,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_q_ecc_reg_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_q_ecc_tmp_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_tmp,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_tmp,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_out,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_out,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_x,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_x,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_out_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_out_a,31,0);
    //char	__VpadToAlign2236[4];
    VL_SIGW(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__ram_initf,2048,1,64);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__file_desc,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__wa_mult_x,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__wa_mult_x_ii,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__wa_mult_x_iii,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_original_data_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_original_data_a,31,0);
    VL_SIGW(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__cread_during_write_mode_mixed_ports,168,0,6);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_byte_size,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_numwords_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_numwords_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_aclr_flag_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_aclr_flag_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_q_tmp2_a_idx,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__init_i,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i2,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i3,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i4,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i5,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__j,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__j2,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__j3,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__k,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__k2,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__k3,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__k4,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_div_wa,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_div_wb,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__j_plus_i2,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__j2_plus_i5,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__j3_plus_i5,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__j_plus_i2_div_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__j2_plus_i5_div_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__j3_plus_i5_div_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__j3_plus_i5_div_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_byteena_count,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__port_a_bit_count_low,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__port_a_bit_count_high,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__port_b_bit_count_low,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__port_b_bit_count_high,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_data_reg_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__temp_wa,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__temp_wa2,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__temp_wa2b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__init_temp,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_data_reg_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__temp_wb,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__temp_wb2,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_q_reg_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_q_tmp_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_q_tmp2_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_q_reg_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_q_tmp_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_q_tmp2_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_q_output_latch,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_q_ecc_reg_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_q_ecc_tmp_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_tmp,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_tmp,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_out,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_out,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_x,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_x,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_out_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_out_a,31,0);
    VL_SIGW(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__ram_initf,2048,1,64);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__file_desc,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__wa_mult_x,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__wa_mult_x_ii,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__wa_mult_x_iii,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_original_data_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_original_data_a,31,0);
    VL_SIGW(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__cread_during_write_mode_mixed_ports,168,0,6);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_byte_size,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_numwords_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_numwords_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_aclr_flag_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_aclr_flag_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_q_tmp2_a_idx,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__init_i,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i2,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i3,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i4,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i5,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__j,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__j2,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__j3,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__k,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__k2,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__k3,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__k4,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_div_wa,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_div_wb,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__j_plus_i2,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__j2_plus_i5,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__j3_plus_i5,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__j_plus_i2_div_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__j2_plus_i5_div_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__j3_plus_i5_div_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__j3_plus_i5_div_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_byteena_count,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__port_a_bit_count_low,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__port_a_bit_count_high,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__port_b_bit_count_low,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__port_b_bit_count_high,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_data_reg_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__temp_wa,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__temp_wa2,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__temp_wa2b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__init_temp,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_data_reg_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__temp_wb,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__temp_wb2,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_q_reg_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_q_tmp_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_q_tmp2_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_q_reg_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_q_tmp_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_q_tmp2_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_q_output_latch,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_q_ecc_reg_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_q_ecc_tmp_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_tmp,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_tmp,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_out,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_out,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_x,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_x,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_a_out_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_byteena_mask_reg_b_out_a,31,0);
    VL_SIGW(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__ram_initf,2048,1,64);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__file_desc,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__wa_mult_x,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__wa_mult_x_ii,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__wa_mult_x_iii,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_original_data_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_original_data_a,31,0);
    VL_SIGW(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__cread_during_write_mode_mixed_ports,168,0,6);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_byte_size,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_numwords_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_numwords_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_aclr_flag_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_aclr_flag_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_q_tmp2_a_idx,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__init_i,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i2,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i3,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i4,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i5,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__j,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__j2,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__j3,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__k,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__k2,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__k3,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__k4,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_div_wa,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_div_wb,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__j_plus_i2,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__j2_plus_i5,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__j3_plus_i5,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__j_plus_i2_div_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__j2_plus_i5_div_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__j3_plus_i5_div_a,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__j3_plus_i5_div_b,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_byteena_count,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__port_a_bit_count_low,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__port_a_bit_count_high,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__port_b_bit_count_low,31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__port_b_bit_count_high,31,0);
    VL_SIG(v__DOT__packet_Display__DOT__hcount,25,0);
    VL_SIG(v__DOT__packet_Display__DOT__vcount,25,0);
    //char	__VpadToAlign3772[4];
    VL_SIG64(v__DOT__input_ram1__DOT__altsyncram_component__DOT__add_reg_a_mult_wa,43,0);
    VL_SIG64(v__DOT__input_ram1__DOT__altsyncram_component__DOT__add_reg_b_mult_wb,43,0);
    VL_SIG64(v__DOT__input_ram1__DOT__altsyncram_component__DOT__add_reg_a_mult_wa_pl_wa,43,0);
    VL_SIG64(v__DOT__input_ram1__DOT__altsyncram_component__DOT__add_reg_b_mult_wb_pl_wb,43,0);
    VL_SIG64(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_ram_block_type,56,0);
    VL_SIG64(v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_data_write_time_a,63,0);
    VL_SIG64(v__DOT__input_ram2__DOT__altsyncram_component__DOT__add_reg_a_mult_wa,43,0);
    VL_SIG64(v__DOT__input_ram2__DOT__altsyncram_component__DOT__add_reg_b_mult_wb,43,0);
    VL_SIG64(v__DOT__input_ram2__DOT__altsyncram_component__DOT__add_reg_a_mult_wa_pl_wa,43,0);
    VL_SIG64(v__DOT__input_ram2__DOT__altsyncram_component__DOT__add_reg_b_mult_wb_pl_wb,43,0);
    VL_SIG64(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_ram_block_type,56,0);
    VL_SIG64(v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_data_write_time_a,63,0);
    VL_SIG64(v__DOT__input_ram3__DOT__altsyncram_component__DOT__add_reg_a_mult_wa,43,0);
    VL_SIG64(v__DOT__input_ram3__DOT__altsyncram_component__DOT__add_reg_b_mult_wb,43,0);
    VL_SIG64(v__DOT__input_ram3__DOT__altsyncram_component__DOT__add_reg_a_mult_wa_pl_wa,43,0);
    VL_SIG64(v__DOT__input_ram3__DOT__altsyncram_component__DOT__add_reg_b_mult_wb_pl_wb,43,0);
    VL_SIG64(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_ram_block_type,56,0);
    VL_SIG64(v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_data_write_time_a,63,0);
    VL_SIG64(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__add_reg_a_mult_wa,43,0);
    VL_SIG64(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__add_reg_b_mult_wb,43,0);
    VL_SIG64(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__add_reg_a_mult_wa_pl_wa,43,0);
    VL_SIG64(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__add_reg_b_mult_wb_pl_wb,43,0);
    VL_SIG64(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_ram_block_type,56,0);
    VL_SIG64(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_data_write_time_a,63,0);
    VL_SIG64(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__add_reg_a_mult_wa,43,0);
    VL_SIG64(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__add_reg_b_mult_wb,43,0);
    VL_SIG64(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__add_reg_a_mult_wa_pl_wa,43,0);
    VL_SIG64(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__add_reg_b_mult_wb_pl_wb,43,0);
    VL_SIG64(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_ram_block_type,56,0);
    VL_SIG64(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_data_write_time_a,63,0);
    VL_SIG64(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__add_reg_a_mult_wa,43,0);
    VL_SIG64(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__add_reg_b_mult_wb,43,0);
    VL_SIG64(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__add_reg_a_mult_wa_pl_wa,43,0);
    VL_SIG64(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__add_reg_b_mult_wb_pl_wb,43,0);
    VL_SIG64(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_ram_block_type,56,0);
    VL_SIG64(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_data_write_time_a,63,0);
    VL_SIG(v__DOT__input_ram1__DOT__altsyncram_component__DOT__mem_data[4096],31,0);
    VL_SIG(v__DOT__input_ram2__DOT__altsyncram_component__DOT__mem_data[4096],31,0);
    VL_SIG(v__DOT__input_ram3__DOT__altsyncram_component__DOT__mem_data[4096],31,0);
    VL_SIG(v__DOT__fifo1__DOT__scfifo_component__DOT__mem_data[5],31,0);
    //char	__VpadToAlign53236[4];
    VL_SIG(v__DOT__fifo2__DOT__scfifo_component__DOT__mem_data[5],31,0);
    //char	__VpadToAlign53260[4];
    VL_SIG(v__DOT__fifo3__DOT__scfifo_component__DOT__mem_data[5],31,0);
    //char	__VpadToAlign53284[4];
    VL_SIG(v__DOT__megamux1__DOT__LPM_MUX_component__DOT__result_pipe[2],31,0);
    VL_SIG(v__DOT__megamux2__DOT__LPM_MUX_component__DOT__result_pipe[2],31,0);
    VL_SIG(v__DOT__megamux3__DOT__LPM_MUX_component__DOT__result_pipe[2],31,0);
    VL_SIG(v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__mem_data[4096],31,0);
    VL_SIG(v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__mem_data[4096],31,0);
    VL_SIG(v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__mem_data[4096],31,0);
    
    // LOCAL VARIABLES
    // Internals; generally not touched by application code
    VL_SIG8(__Vdly__v__DOT__input_ram_wren1,0,0);
    VL_SIG8(__Vdly__v__DOT__input_ram_wren2,0,0);
    VL_SIG8(__Vdly__v__DOT__input_ram_wren3,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo1__DOT__scfifo_component__DOT__read_id,1,0);
    VL_SIG8(__Vdly__v__DOT__fifo1__DOT__scfifo_component__DOT__count_id,1,0);
    VL_SIG8(__Vdly__v__DOT__fifo1__DOT__scfifo_component__DOT__full_flag,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo1__DOT__scfifo_component__DOT__empty_flag,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo1__DOT__scfifo_component__DOT__empty_latency1,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo1__DOT__scfifo_component__DOT__set_q_to_x,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo1__DOT__scfifo_component__DOT__set_q_to_x_by_empty,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo1__DOT__scfifo_component__DOT__write_id,1,0);
    VL_SIG8(__Vdly__v__DOT__fifo1__DOT__scfifo_component__DOT__write_flag,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo1__DOT__scfifo_component__DOT__write_latency1,1,0);
    VL_SIG8(__Vdly__v__DOT__fifo1__DOT__scfifo_component__DOT__write_latency2,1,0);
    VL_SIG8(__Vdly__v__DOT__fifo1__DOT__scfifo_component__DOT__data_shown,3,0);
    VL_SIG8(__Vdly__v__DOT__fifo1__DOT__scfifo_component__DOT__data_ready,3,0);
    VL_SIG8(__Vdlyvset__v__DOT__fifo1__DOT__scfifo_component__DOT__mem_data__v0,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo2__DOT__scfifo_component__DOT__read_id,1,0);
    VL_SIG8(__Vdly__v__DOT__fifo2__DOT__scfifo_component__DOT__count_id,1,0);
    VL_SIG8(__Vdly__v__DOT__fifo2__DOT__scfifo_component__DOT__full_flag,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo2__DOT__scfifo_component__DOT__empty_flag,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo2__DOT__scfifo_component__DOT__empty_latency1,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo2__DOT__scfifo_component__DOT__set_q_to_x,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo2__DOT__scfifo_component__DOT__set_q_to_x_by_empty,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo2__DOT__scfifo_component__DOT__write_id,1,0);
    VL_SIG8(__Vdly__v__DOT__fifo2__DOT__scfifo_component__DOT__write_flag,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo2__DOT__scfifo_component__DOT__write_latency1,1,0);
    VL_SIG8(__Vdly__v__DOT__fifo2__DOT__scfifo_component__DOT__write_latency2,1,0);
    VL_SIG8(__Vdly__v__DOT__fifo2__DOT__scfifo_component__DOT__data_shown,3,0);
    VL_SIG8(__Vdly__v__DOT__fifo2__DOT__scfifo_component__DOT__data_ready,3,0);
    VL_SIG8(__Vdlyvset__v__DOT__fifo2__DOT__scfifo_component__DOT__mem_data__v0,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo3__DOT__scfifo_component__DOT__read_id,1,0);
    VL_SIG8(__Vdly__v__DOT__fifo3__DOT__scfifo_component__DOT__count_id,1,0);
    VL_SIG8(__Vdly__v__DOT__fifo3__DOT__scfifo_component__DOT__full_flag,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo3__DOT__scfifo_component__DOT__empty_flag,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo3__DOT__scfifo_component__DOT__empty_latency1,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo3__DOT__scfifo_component__DOT__set_q_to_x,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo3__DOT__scfifo_component__DOT__set_q_to_x_by_empty,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo3__DOT__scfifo_component__DOT__write_id,1,0);
    VL_SIG8(__Vdly__v__DOT__fifo3__DOT__scfifo_component__DOT__write_flag,0,0);
    VL_SIG8(__Vdly__v__DOT__fifo3__DOT__scfifo_component__DOT__write_latency1,1,0);
    VL_SIG8(__Vdly__v__DOT__fifo3__DOT__scfifo_component__DOT__write_latency2,1,0);
    VL_SIG8(__Vdly__v__DOT__fifo3__DOT__scfifo_component__DOT__data_shown,3,0);
    VL_SIG8(__Vdly__v__DOT__fifo3__DOT__scfifo_component__DOT__data_ready,3,0);
    VL_SIG8(__Vdlyvset__v__DOT__fifo3__DOT__scfifo_component__DOT__mem_data__v0,0,0);
    VL_SIG8(__Vdly__v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_read_flag_b,0,0);
    VL_SIG8(__Vdly__v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_read_flag_b,0,0);
    VL_SIG8(__Vdly__v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_read_flag_b,0,0);
    VL_SIG8(__Vdly__v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_read_flag_b,0,0);
    VL_SIG8(__Vdly__v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_read_flag_b,0,0);
    VL_SIG8(__Vdly__v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_read_flag_b,0,0);
    VL_SIG8(__VinpClk__TOP__v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(__VinpClk__TOP__v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(__VinpClk__TOP__v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(__VinpClk__TOP__v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(__VinpClk__TOP__v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(__VinpClk__TOP__v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(__Vclklast__TOP__clk,0,0);
    VL_SIG8(__Vclklast__TOP__reset,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_outdata_aclr_a_prev,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_outdata_aclr_b_prev,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_good_to_write_a2,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__input_ram1__DOT__altsyncram_component__DOT__i_good_to_write_b2,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_outdata_aclr_a_prev,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_outdata_aclr_b_prev,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_good_to_write_a2,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__input_ram2__DOT__altsyncram_component__DOT__i_good_to_write_b2,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_outdata_aclr_a_prev,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_outdata_aclr_b_prev,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_good_to_write_a2,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__input_ram3__DOT__altsyncram_component__DOT__i_good_to_write_b2,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_outdata_aclr_a_prev,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_outdata_aclr_b_prev,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_good_to_write_a2,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__buffer__DOT__ram1__DOT__altsyncram_component__DOT__i_good_to_write_b2,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_outdata_aclr_a_prev,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_outdata_aclr_b_prev,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_good_to_write_a2,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__buffer__DOT__ram2__DOT__altsyncram_component__DOT__i_good_to_write_b2,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_write_flag_a,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_outdata_aclr_a_prev,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_outdata_aclr_b_prev,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_good_to_write_a2,0,0);
    VL_SIG8(__Vchglast__TOP__v__DOT__buffer__DOT__ram3__DOT__altsyncram_component__DOT__i_good_to_write_b2,0,0);
    //char	__VpadToAlign102563[1];
    VL_SIG16(__Vdly__v__DOT__input_ram_wr_add1,11,0);
    VL_SIG16(__Vdly__v__DOT__input_ram_wr_add2,11,0);
    VL_SIG16(__Vdly__v__DOT__input_ram_wr_add3,11,0);
    VL_SIG16(__Vdly__v__DOT__buffer__DOT__ram_wr_add1,11,0);
    VL_SIG16(__Vdly__v__DOT__buffer__DOT__ram_wr_add2,11,0);
    VL_SIG16(__Vdly__v__DOT__buffer__DOT__ram_wr_add3,11,0);
    VL_SIG16(__Vdly__v__DOT__buffer__DOT__ram_rd_add1,11,0);
    VL_SIG16(__Vdly__v__DOT__buffer__DOT__ram_rd_add2,11,0);
    VL_SIG16(__Vdly__v__DOT__buffer__DOT__ram_rd_add3,11,0);
    //char	__VpadToAlign102582[2];
    VL_SIG(v__DOT__fifo1__DOT__scfifo_component__DOT____Vlvbound4,31,0);
    VL_SIG(v__DOT__fifo2__DOT__scfifo_component__DOT____Vlvbound4,31,0);
    VL_SIG(v__DOT__fifo3__DOT__scfifo_component__DOT____Vlvbound4,31,0);
    VL_SIG(__Vdly__v__DOT__fifo1__DOT__scfifo_component__DOT__wrt_count,31,0);
    VL_SIG(__Vdly__v__DOT__fifo2__DOT__scfifo_component__DOT__wrt_count,31,0);
    VL_SIG(__Vdly__v__DOT__fifo3__DOT__scfifo_component__DOT__wrt_count,31,0);
    VL_SIG(__Vm_traceActivity,31,0);
    
    // INTERNAL VARIABLES
    // Internals; generally not touched by application code
    VVGA_LED__Syms*	__VlSymsp;		// Symbol table
    
    // PARAMETERS
    // Parameters marked /*verilator public*/ for use by application code
    
    // CONSTRUCTORS
  private:
    VVGA_LED& operator= (const VVGA_LED&);	///< Copying not allowed
    VVGA_LED(const VVGA_LED&);	///< Copying not allowed
  public:
    /// Construct the model; called by application code
    /// The special name  may be used to make a wrapper with a
    /// single model invisible WRT DPI scope names.
    VVGA_LED(const char* name="TOP");
    /// Destroy the model; called (often implicitly) by application code
    ~VVGA_LED();
    /// Trace signals in the model; called by application code
    void trace (VerilatedVcdC* tfp, int levels, int options=0);
    
    // USER METHODS
    
    // API METHODS
    /// Evaluate the model.  Application must call when inputs change.
    void eval();
    /// Simulation complete, run final blocks.  Application must call on completion.
    void final();
    
    // INTERNAL METHODS
  private:
    static void _eval_initial_loop(VVGA_LED__Syms* __restrict vlSymsp);
  public:
    void __Vconfigure(VVGA_LED__Syms* symsp, bool first);
  private:
    static IData	_change_request(VVGA_LED__Syms* __restrict vlSymsp);
  public:
    static void	_combo__TOP__15(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_combo__TOP__2(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_combo__TOP__25(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_eval(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_eval_initial(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_eval_settle(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_initial__TOP(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__19(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__20(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__21(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__22(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__23(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__24(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__10(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__11(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__12(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__14(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__16(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__17(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__3(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__4(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__5(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__6(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__7(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__8(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__9(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_settle__TOP__1(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_settle__TOP__13(VVGA_LED__Syms* __restrict vlSymsp);
    static void	_settle__TOP__18(VVGA_LED__Syms* __restrict vlSymsp);
    static void	traceChgThis(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__10(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__11(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__12(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__13(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__14(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__15(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__16(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__17(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__18(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__19(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__2(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__20(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__21(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__22(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__23(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__24(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__25(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__26(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__27(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__28(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__29(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__3(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__30(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__31(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__32(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__33(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__34(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__35(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__36(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__37(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__38(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__39(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__4(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__40(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__5(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__6(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__7(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__8(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__9(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceFullThis(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceFullThis__1(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceInitThis(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceInitThis__1(VVGA_LED__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceInit (VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceFull (VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceChg  (VerilatedVcd* vcdp, void* userthis, uint32_t code);
} VL_ATTR_ALIGNED(128);

#endif  /*guard*/
